export { default as Eye } from "./eye.png";
export { default as ArgIcon } from "./argIcon.png";
export { default as IconSearch } from "./lupa.png";
export { default as usdtIcon } from "./usdt.png";
export { default as LogoArg } from "./argIcon.png";
export { default as Lemon } from "./lemon-lemon.png";
export { default as openSea } from "./openSea.png";
export { default as LemonNation } from "./nation.png";
export { default as Coin } from "./coin.png";
